services:
    db:
        image: postgres:15
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    backend:
        build: ./backend
        command: .venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
        volumes:
            - ./backend:/app
            - ./backend/data:/app/data
            - ./backend/audio_files:/app/audio_files
        env_file:
            - .env
        environment:
            DATABASE_URL: ${DATABASE_URL_DOCKER}
            # Add other env vars as needed
        depends_on:
            - db
        ports:
            - "8000:8000"
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/app
        command: yarn dev --host 0.0.0.0
        ports:
            - "5173:5173"
        depends_on:
            - backend
volumes:
    pgdata:
