services:
    db:
        image: postgres:15
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    backend:
        build: ./backend
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        volumes:
            - ./backend:/app
            - ./data:/data
            - ./backend/audio_files:/app/audio_files
        depends_on:
            - db
        ports:
            - "8000:8000"
    frontend:
        build:
            context: ./frontend
            args:
                - VITE_API_URL=http://backend:8000
        environment:
            - NODE_ENV=production
            - VITE_API_URL=http://backend:8000
        command: ["nginx", "-g", "daemon off;"]
        ports:
            - "80:80"
        depends_on:
            - backend
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
    celery:
        build:
            context: ./backend
            dockerfile: celery_scripts/Dockerfile
        working_dir: /app/celery_scripts
        volumes:
            - ./backend:/app
            - ./data:/data
            - ./backend/audio_files:/app/audio_files
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_BACKEND_URL=redis://redis:6379/0
        depends_on:
            - backend
            - redis

volumes:
    pgdata:
        driver: local
    redis_data:
        driver: local
