name: acronym
version: 1.7.0.11

dependencies:
  - base
  - test

library:
  exposed-modules: Acronym
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - test

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - acronym
      - hspec