"""Add cover_image_paths to Recipe

Revision ID: 68bfb4d88de0
Revises: aea05df33037
Create Date: 2025-07-30 00:04:41.627855

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68bfb4d88de0"
down_revision: Union[str, Sequence[str], None] = "aea05df33037"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("cover_image_paths", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "cover_image_paths")
    # ### end Alembic commands ###
