"""Add cover_image_paths to Recipe

Revision ID: 907de54da71f
Revises: 68bfb4d88de0
Create Date: 2025-07-30 00:49:52.820303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907de54da71f'
down_revision: Union[str, Sequence[str], None] = '68bfb4d88de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('cover_image_paths', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'cover_image_paths')
    # ### end Alembic commands ###
